# -*- coding: utf-8 -*-
"""MLA_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VgaxXI4AiLzIPBR-tACkruGcprtzifyl
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("Color Balls.csv")
print(df)

features = ['Room','Partitions','Rows','Columns']

X = df[features]
y = df['Color']

print(X)
print(y)

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt

dtree = DecisionTreeClassifier()
dtree = dtree.fit(X, y)

tree.plot_tree(dtree, feature_names=features)

